import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Arisha Figma Hackathon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <Header /> {/* Header placed inside the body */}
        <main>{children}</main> {/* Main content wrapped in semantic <main> */}
        <Footer /> {/* Footer also placed inside the body */}
      </body>
    </html>
  );
}
